/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import static oop.devID.deveId;
/**
 *
 * @author Donya
 */
public class adminprojectlist extends javax.swing.JFrame {

    /**
     * Creates new form adminprojectlist
     */
    public adminprojectlist() {
        initComponents();
    }
//       public ArrayList<bug> bList(){
//    ArrayList<bug> bList= new ArrayList<>();
//           try {
//            String url = "jdbc:sqlserver://localhost\\DESKTOP-NVH7PIU\\SQLEXPRESS:1433;databaseName=OOP";
//            String username = "donia";
//            String password = "1234";
//            Connection con = DriverManager.getConnection(url, username, password);
//            Statement stmt = con.createStatement();
//          
//            String Query = "select * from bugs where pID='"+Integer.parseInt(pID.getText())+"'";
//              ResultSet rs= stmt.executeQuery(Query);
//              bug b;
//             while(rs.next())
//            
//             
//                  stmt.execute(Query);
//            JOptionPane.showMessageDialog(null, "bug added to database");
//           
//      
//          
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.toString());
//
//        } 
//    
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessuse = new javax.swing.JButton();
        adview = new javax.swing.JLabel();
        listofpro = new javax.swing.JLabel();
        pID = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accessuse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        accessuse.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_group2_309041.png")); // NOI18N
        accessuse.setText("Users");
        accessuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessuseActionPerformed(evt);
            }
        });
        getContentPane().add(accessuse, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, 58));

        adview.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        adview.setForeground(new java.awt.Color(0, 51, 102));
        adview.setText("Admin");
        getContentPane().add(adview, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, -1));

        listofpro.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        listofpro.setText("project id");
        getContentPane().add(listofpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 180, 35));

        pID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDActionPerformed(evt);
            }
        });
        getContentPane().add(pID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 270, -1));

        enter.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        enter.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_Enter_728934.png")); // NOI18N
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\Bioanalysis (embedded system)\\edited\\069e684a-86b0-4e8c-b3fd-42291fa724de.jpg")); // NOI18N
        jLabel1.setText("    ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessuseActionPerformed

    new Userlist().setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_accessuseActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
  Oop d= new Oop();
   d.project(pID);
 
//        try {
//            String url = "jdbc:sqlserver://localhost\\DESKTOP-NVH7PIU\\SQLEXPRESS:1433;databaseName=OOP";
//            String username = "donia";
//            String password = "1234";
//            Connection con = DriverManager.getConnection(url, username, password);
//
//            String Query = "Select * from  bugs where pID='" + Integer.parseInt(pID.getText()) + "' ";
//            Statement stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery(Query);
//            if (rs.next() == true) {
//
//                new projectbugTable().setVisible(true);
//
//            } else {
//                JOptionPane.showMessageDialog(null, "user is not found");
//            }
//
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.toString());
//        }
       // TODO add your handling code here:
    }//GEN-LAST:event_enterActionPerformed

    private void pIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminprojectlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminprojectlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminprojectlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminprojectlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminprojectlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessuse;
    private javax.swing.JLabel adview;
    public static javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel listofpro;
    public static javax.swing.JTextField pID;
    // End of variables declaration//GEN-END:variables
}
