/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Donya
 */
public class devID extends javax.swing.JFrame {

    /**
     * Creates new form devID
     */
    public devID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deveId = new javax.swing.JTextField();
        entdev = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Developer ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 280, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        deveId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deveId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deveIdActionPerformed(evt);
            }
        });
        getContentPane().add(deveId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 300, 41));

        entdev.setBackground(new java.awt.Color(204, 204, 204));
        entdev.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        entdev.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_login_enter_sign_in_input_access_3994380.png")); // NOI18N
        entdev.setText("Enter");
        entdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entdevActionPerformed(evt);
            }
        });
        getContentPane().add(entdev, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 176, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\G\\Desktop\\c86acb51-bacd-4128-baba-b37b27ebb4af.jpg")); // NOI18N
        jLabel3.setText("      ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -3, 870, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entdevActionPerformed
//  try {
//            String url = "jdbc:sqlserver://localhost\\DESKTOP-NVH7PIU\\SQLEXPRESS:1433;databaseName=OOP";
//            String username = "donia";
//            String password = "1234";
//            Connection con = DriverManager.getConnection(url, username, password);
//
//            String Query = "Select * from  developer1 where dev_id='" + Integer.parseInt(deveId.getText()) + "' ";
//            Statement stmt = con.createStatement();
//            ResultSet rs = stmt.executeQuery(Query);
//            if (rs.next() == true) {
//
//                new developerviiew().setVisible(true);
//
//            } else {
//                JOptionPane.showMessageDialog(null, "user is not found");
//            }
//
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(null, ex.toString());
//        }
    
 Oop d= new Oop();
   d.devID(Integer.parseInt(deveId.getText()));

        // TODO add your handling code here:
    }//GEN-LAST:event_entdevActionPerformed

    private void deveIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deveIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deveIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(devID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(devID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(devID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(devID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new devID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField deveId;
    public javax.swing.JButton entdev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
