/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.management.Query;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.PasswordAuthentication;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.mail.Transport;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Donya
 */
public class Etodev extends javax.swing.JFrame {

    /**
     * Creates new form Etodev
     */
    public Etodev() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *   String Query = "Select * from  tester where testID='" + parseInt + "' and t_name='" + tname.getText() + "'";
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tom = new javax.swing.JLabel();
        fromm = new javax.swing.JLabel();
        Subjectm = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        To = new javax.swing.JTextField();
        From = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ma = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        sendEmail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passw = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tom.setForeground(new java.awt.Color(255, 255, 255));
        tom.setText("To");
        getContentPane().add(tom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        fromm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fromm.setForeground(new java.awt.Color(255, 255, 255));
        fromm.setText("From");
        getContentPane().add(fromm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, 27));

        Subjectm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Subjectm.setForeground(new java.awt.Color(255, 255, 255));
        Subjectm.setText("Subject");
        getContentPane().add(Subjectm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Message");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 411, -1));
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 411, -1));
        getContentPane().add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 411, -1));

        ma.setColumns(20);
        ma.setRows(5);
        jScrollPane1.setViewportView(ma);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 411, 310));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 140, -1));

        sendEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendEmail.setText("Send Email");
        sendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailActionPerformed(evt);
            }
        });
        getContentPane().add(sendEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 109, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 110, -1));
        getContentPane().add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 411, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\project\\wolf.jpg")); // NOI18N
        jLabel3.setText("     ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1250, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void sendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailActionPerformed
 

 Oop e= new Oop();
   e.email( To, From, passw,ma, subject);
   
////String Toemail= To.getText();
////       String Fromemail= From.getText();
////       String FromemailPass= passw.getText();
////       String Subjects= subject.getText();
////    Properties prop= new Properties();
////   prop.put("mail.smtp.host", "smtp.gmail.com");
////    prop.put("mail.smtp.port", "587");
////    prop.put("mail.smtp.starttls.enable", "true");
////    prop.put("mail.smtp.auth", "true");
////      Session session = Session.getDefaultInstance(prop,new Authenticator() {
////            @Override
////            protected PasswordAuthentication getPasswordAuthentication() {
////                return new PasswordAuthentication (Fromemail , FromemailPass); 
////            }
////        });
////
////      
////            
////            
////    try {
////    MimeMessage message= new MimeMessage(session);
////    message.setFrom(new InternetAddress(Fromemail));
////    message.addRecipient(Message.RecipientType.TO, new InternetAddress(Toemail));
////    message.setSubject(Subjects);
////    message.setText(ma.getText());
////    Transport.send(message);
////      JOptionPane.showMessageDialog(null, "Email sent");
////    }
////    catch (Exception ex){
////        System.out.println(""+ex);
////    }
   

    
    }//GEN-LAST:event_sendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etodev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etodev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etodev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etodev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etodev().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField From;
    private javax.swing.JLabel Subjectm;
    public static javax.swing.JTextField To;
    private javax.swing.JLabel fromm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea ma;
    private javax.swing.JPasswordField passw;
    public static javax.swing.JButton sendEmail;
    public static javax.swing.JTextField subject;
    private javax.swing.JLabel tom;
    // End of variables declaration//GEN-END:variables
}
