/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;
import java.sql.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author Donya
 */
public class Newbug extends javax.swing.JFrame {

    /**
     * Creates new form Newbug
     */
    public Newbug() {
        initComponents();
    } 
/*public ArrayList<bug> userList()
{ ArrayList<bug> userList= new ArrayList<>();
try}*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bugID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Namebug = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bugtype = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priority = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        level = new javax.swing.JTextField();
        projectID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bugdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addbug = new javax.swing.JButton();
        statusID = new javax.swing.JTextField();
        projecID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        devID = new javax.swing.JTextField();
        screenshot = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New bug");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 130, -1, -1));
        getContentPane().add(bugID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 211, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 178, -1, -1));
        getContentPane().add(Namebug, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 132, 211, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 78, -1, -1));
        getContentPane().add(bugtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 211, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Priority");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 234, -1, -1));
        getContentPane().add(priority, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 236, 211, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Level");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 285, -1, -1));
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 287, 211, -1));

        projectID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        projectID.setText("ProjectID");
        getContentPane().add(projectID, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 329, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Bug date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 379, -1, -1));
        getContentPane().add(bugdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 381, 211, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("StatusID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 426, -1, -1));

        addbug.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addbug.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_netvibes-social-media-logo_2215361.png")); // NOI18N
        addbug.setText("Add");
        addbug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbugActionPerformed(evt);
            }
        });
        getContentPane().add(addbug, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));
        getContentPane().add(statusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 428, 211, -1));
        getContentPane().add(projecID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 331, 211, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("developer id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        devID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devIDActionPerformed(evt);
            }
        });
        getContentPane().add(devID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 211, -1));

        screenshot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenshotActionPerformed(evt);
            }
        });
        getContentPane().add(screenshot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 211, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("screenshot");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\G\\Desktop\\98d31b35-5d6f-4402-8867-59d66ec53f19.jpg")); // NOI18N
        jLabel11.setText("        ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbugActionPerformed
   Oop n= new Oop();
   n.addbug(bugID, Namebug, bugtype, priority, level, projecID, bugdate, statusID, devID,screenshot);
      
      
        // TODO add your handling code here:
    }//GEN-LAST:event_addbugActionPerformed

    private void devIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devIDActionPerformed
     
       // TODO add your handling code here:
    }//GEN-LAST:event_devIDActionPerformed

    private void screenshotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenshotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screenshotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Newbug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Newbug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Newbug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Newbug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Newbug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Namebug;
    private javax.swing.JButton addbug;
    private javax.swing.JTextField bugID;
    private javax.swing.JTextField bugdate;
    private javax.swing.JTextField bugtype;
    private javax.swing.JTextField devID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField level;
    private javax.swing.JTextField priority;
    private javax.swing.JTextField projecID;
    private javax.swing.JLabel projectID;
    private javax.swing.JTextField screenshot;
    private javax.swing.JTextField statusID;
    // End of variables declaration//GEN-END:variables
}
