/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oop.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Donya
 */
public class Userlist extends javax.swing.JFrame {

    /**
     * Creates new form Userlist
     */
    public Userlist() {
        initComponents(); 
        DisplayTable();
    }
    
          
    public void DisplayTable(){
  
      try{
        String url="jdbc:sqlserver://localhost\\DESKTOP-NVH7PIU\\SQLEXPRESS:1433;databaseName=OOP";
      String username="donia";
      String password="1234";
      Connection con = DriverManager.getConnection(url,username,password);
      String query="SELECT * FROM users";
      Statement st=con.createStatement();
      ResultSet rs=st.executeQuery(query);
      
         userstable.setModel(DbUtils.resultSetToTableModel(rs));
      
      }
       catch(SQLException ex)
    { JOptionPane.showMessageDialog(null, ex.toString());
    
    
    }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        uID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        updateu = new javax.swing.JButton();
        deleteu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        roleID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Users");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 140, -1));

        uID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uIDActionPerformed(evt);
            }
        });
        getContentPane().add(uID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("UserID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("role_ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        user_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 210, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, 30));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_simpline_2_2305585.png")); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 383, -1, -1));

        updateu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateu.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\Update.png")); // NOI18N
        updateu.setText("Update");
        updateu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateuActionPerformed(evt);
            }
        });
        getContentPane().add(updateu, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 383, -1, 73));

        deleteu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteu.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\PL2\\icon\\iconfinder_simpline_12_2305636.png")); // NOI18N
        deleteu.setText("Delete");
        deleteu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuActionPerformed(evt);
            }
        });
        getContentPane().add(deleteu, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 383, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Username");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 120, 30));

        roleID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(roleID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 210, 30));

        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "userID", "roleID", "username", "password"
            }
        ));
        jScrollPane1.setViewportView(userstable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 24, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\College resources\\Terms\\Third Term\\Bioanalysis (embedded system)\\edited\\069e684a-86b0-4e8c-b3fd-42291fa724de.jpg")); // NOI18N
        jLabel6.setText("    ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
 Oop m= new Oop();
        m.adduser(uID, user_name, pass, roleID);
       
    }//GEN-LAST:event_addActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void updateuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateuActionPerformed
  Oop u= new Oop();
  u.updateuser(user_name, pass, roleID, uID);
        
         // TODO add your handling code here:
    }//GEN-LAST:event_updateuActionPerformed

    private void uIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uIDActionPerformed

    private void deleteuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuActionPerformed
Oop d= new Oop();
d.deleteuser(uID);


// TODO add your handling code here:
    }//GEN-LAST:event_deleteuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton deleteu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField roleID;
    private javax.swing.JTextField uID;
    private javax.swing.JButton updateu;
    private javax.swing.JTextField user_name;
    private javax.swing.JTable userstable;
    // End of variables declaration//GEN-END:variables
}
